# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 838cb3df029e61c5c051c0e201a3aac240a9654609648067c51561ad6193667976d8985dff131afe356b89fbcdd5ac0e64b1746accb211d206037bd52d16a77b

test:
  secret_key_base: dfc29376f44b97bdb5daee1d179cbbbdb4d61d57b47a7e9f87199cf5ec85e7499cd6437aecec043fc026736ef5d878159fe4a5451ba971171b877080a62182d5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
